name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Publish Python Package in PyPI manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12 manually without uses
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-virtualenv
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask>=3.0.3 click>=8.1.7 pytest>=8.3.3 pytest-flask>=1.3.0 python-dotenv>=1.0.1

      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
